version: '3.4'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=shorty
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

volumes:
  db-data: {}
